### ISSUE TITLE
about training..

### ISSUE THREAD

**Issue by sandys** [beraldofilippo/android-hpe#2]
hi beraldo,
awesome project! so after looking at your conversation [here]( https://sourceforge.net/p/dclib/discussion/442518/thread/e80e526e/), you are one of the few people that has tried retraining the landmark detection data.

I'm trying to attempt it for the very first time - can you talk about whether you were successful or not (and the reason) ? in the thread you were talking about different models - did not understand the reason.

**Comment by beraldofilippo** [comment]
Hi, thanks for your interest in the project.

Unfortunately I did not manage to get a good precision on the models that I trained, and since I do not know the reason why I couldn't succeed :)

As for the "models" I think you're referring to the fact that I trained three different models, one for the left looking faces, one for the right looking faces (using the mirrored images from the left looking) and one for the front. 
The reason I did it is that the algorithm couldn't use a single model to detect such extreme angles of pose of the head, therefore I trained three separate models and ran them concurrently on each image, taking the detection with highest confidence.
While I managed to get a proper detection for the rects on the faces and a fairly precise detection whether it was a front looking vs left looking vs right looking face I can't say the same of the precision of the landmark detection, it was too imprecise.

I decided to use the standard provided models for the detection of face pose and landmark detection, and to complete my project with that one.

Good luck with your experiments, please do let me know if you produce something interesting!
