### ISSUE TITLE
Front camera face detection problem

### ISSUE THREAD

**Issue by nsojib** [beraldofilippo/android-hpe#3]
Most of the time it failed to detect face and so pose estimation was not worked. I fed manual image by capturing a photo using other apps than it works fine. I have tested with HTC.

**Comment by beraldofilippo** [comment]
Yeah, then what's the problem here?
You simply told me it does not work, any issue with it?
How am I supposed to help you?

On 26 Aug 2017 20:01, "noushad-sust" <notifications@github.com> wrote:

Most of the time it failed to detect face and so pose estimation was not
worked. I fed manual image by capturing a photo using other apps than it
works fine. I have tested with HTC.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/beraldofilippo/android-hpe/issues/3>, or mute the thread

**Comment by nsojib** [comment]
Here what i have found from log monitor
08-27 00:26:13.985 7017-7160/com.beraldo.hpe I/native: jni_head_pose_det.cpp:56 Number of faces detected: 0

It doesn't detect my face, how can I solve this?

**Comment by nsojib** [comment]
public void onImageAvailable(final ImageReader reader) 
in this method,  I saved the bitmap and found it greenish.
So, in my case conversion to bitmap not working properly.

**Comment by nsojib** [comment]
Actually there is a problem in camera api for api version 21. It works for api version > 21.

**Comment by beraldofilippo** [comment]
I'm glad that you found what the problem was and it now works. Using the camera on these devices has proven to be really flaky :/
